#!/usr/bin/env sh

# for this to work you must configure sudo such that
# it will be able to run the command without password

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# .. more yabai startup stuff
yabai -m config layout bsp
yabai -m config window_placement first_child
yabai -m config window_topmost on
yabai -m config mouse_modifier fn

yabai -m signal --add event=window_created action='ymsp window-created'
yabai -m signal --add event=application_launched action='ymsp window-created'

ymsp on-yabai-start
